apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: zdocs-local

resources:
- ../../base
- secret.yaml

patchesStrategicMerge:
- deployment.yaml

images:
- name: chat-proxy
  newName: chat-proxy
  newTag: local