apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: zdocs-local

resources:
- ../../base

patchesStrategicMerge:
- deployment.yaml

images:
- name: docusaurus
  newName: docusaurus
  newTag: latest